version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:root@mongodb:27017/"
      SPRING_DATA_MONGODB_DATABASE: "egtmanager"
    networks:
      - production-network

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - production-network

volumes:
  mongodb-data:

networks:
  production-network:
    driver: bridge